# git:
#   depth: 3
#   submodules: false
# branches:
#   only:
#   - master

dist:     bionic    

language: cpp
os:
    - linux
    - osx
  
compiler:
    - gcc
    - clang
jobs:
    exclude:
        - os:       osx
          compiler: gcc
        - os:  osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
        - os:  osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release
install:
    # скрипт настройки среды и установки зависимостей:
    - source travis/install-$TRAVIS_OS_NAME.sh

script:
    # скрипт сборки и тестирования проекта:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - cmake --build .
#    - ctest --output-on-failure