# git:
#   depth: 3
#   submodules: false
# branches:
#   only:
#   - master

dist: bionic
language: cpp
os:
    - linux
    - osx
compiler:
    - gcc
    - clang

addons:
  apt:
    packages:
        - libxrandr-dev
        - libxinerama-dev
        - libxcursor-dev
        - libxi-dev
        - libglu1-mesa-dev
        - freeglut3-dev
        - mesa-common-dev

jobs:
  # include:
  #     - os: linux
  #       # sudo: false
  #       name: "ubuntu x11"
        

  exclude:
      - os:       osx
        compiler: gcc
      - os:  osx
        env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
      - os:  osx
        env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release

# before_install:
#   - sudo apt install libxrandr-dev -y
install:
    # скрипт настройки среды и установки зависимостей:
    - source travis/install-$TRAVIS_OS_NAME.sh

script:
    # скрипт сборки и тестирования проекта:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION
    - cmake --build .
#    - ctest --output-on-failure